### ISSUE TITLE
Sync goes on forever year 2030+

### ISSUE THREAD

**Issue by StroescuDiana** [hk21702/Notion-Google-Cal-JS#68]
*Make Sure You Are On The Latest **Main Branch** Version Before Reporting A Bug!!!*
@hk21702 

**Include the following information: **
- [08f9caa](https://github.com/hk21702/YA-GCal-Notion-Sync-Script/commit/08f9caa1a32f4bd245a990ff7c30e5255f18435f)

**Describe the bug**
Evrything works fine, except that it goes on forever. I stopped the run and it reached 2090.
**Screenshots**
<img width="192" alt="Screenshot 2024-05-28 at 19 40 12" src="https://github.com/hk21702/YA-GCal-Notion-Sync-Script/assets/129664856/93e2f57d-5fb4-4eed-93e2-5fed4d7fc373">

**Comment by hk21702** [comment]
I think this is just a weird thing with how Google handles repeating events that have no end date. I've seen it in my usage, but it seems harmless unless it causes a runtime time out. Can you confirm that the events that keep populating are repeating events? If so, it should be fine to just let the run keep going. Eventually, it will stop on its own. Worst case, the run times out, and the result is the same as you manually stopping the run.  

I could add a check to stop the run if it goes past a certain date, but with how the tokens are handled, it is likely the result would be the same as if the run timed out if it were to time out.

**Comment by StroescuDiana** [comment]
Yes, they are repeating events. I don't like that it keeps running, because it takes up battery and probably memory too.
